site_name: Mailing Tools
site_description: Tools supporting mass mailing
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.mailingtools

theme:
  name: material

nav:
  - Introduction: index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
